# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wvh8QELbVmg-jyasA-kJ1IbakBQht8CA
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/gdrive')

ruta = "/gdrive/MyDrive/mineria/newData.csv"
data = pd.read_csv(ruta, encoding="latin1")

X = data[['loan']]
y = data['default']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)



print(classification_report(y_test, y_pred))

plt.scatter(X['loan'], y, c=y, cmap='rainbow')  # Grafica los puntos de datos con colores según la etiqueta
plt.plot(X['loan'], -(model.coef_[0] * X['loan'] + model.intercept_) / model.coef_[0], color='black')  # Grafica la línea de separación
plt.xlabel('Loan')
plt.ylabel('Default')
plt.title('Regresión Logística')
plt.show()