# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGhbbbyDv84UsQjtdYMML8Nd2v99osLC
"""

#lmportamos librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Lectura
from google.colab import drive
drive.mount('/gdrive')

ruta = "/gdrive/MyDrive/vehiculos_procesado.csv"
data = pd.read_csv(ruta, encoding='latin')

data.head()

# Damos valores a las variables.
X = data[['desplazamiento', 'cilindros']]
y = data['co2']
data.shape

#Separamos los datos para entrenamiento del modelo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

reg = LinearRegression().fit(X_train, y_train)

# Realizamos predicciones
y_pred = reg.predict(X_test)

# Coeficiente
print(reg.coef_)

# Sacamos el error cuadrático medio
mse = mean_squared_error(y_test, y_pred)
print("Error cuadrático medio:", mse)

# Dispersión de la variables con respecto a CO2 (graficamos)

import seaborn as sns

sns.pairplot(data, x_vars=['desplazamiento','cilindros','consumo'], y_vars='co2', size=7, aspect=0.8,kind = 'reg')

