# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODXGNL5sQhzASPEZvrG_zxqEqvIRnYC0
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.datosmundial.com/america/mexico/crecimiento-poblacional.php'

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

table = soup.find('table', class_='std100')

rows = table.find_all('tr')[1:]

for fila in rows:
    datos = fila.find_all('td')
    año = datos[0].get_text()
    poblacion = datos[1].get_text()
    cambio = datos[2].get_text()
    natalidad = datos[3].get_text()
    Tasa = datos[4].get_text()
    print(f'Year: {año}, Poblation: {poblacion} , Change {cambio}, Birth rate {natalidad}, Death rate {Tasa} ' )

